<?php

namespace App;


use App\Scopes\BuyerScope;
use App\Transformers\BuyerTransformer;

/**
 * App\Buyer
 *
 * @property int $id
 * @property string $name
 * @property string $email
 * @property string $password
 * @property string|null $remember_token
 * @property string $verified
 * @property string|null $verification_token
 * @property string $admin
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property \Illuminate\Support\Carbon|null $deleted_at
 * @property-read \Illuminate\Notifications\DatabaseNotificationCollection|\Illuminate\Notifications\DatabaseNotification[] $notifications
 * @property-read int|null $notifications_count
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Transaction[] $transactions
 * @property-read int|null $transactions_count
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Buyer newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Buyer newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Buyer query()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Buyer whereAdmin($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Buyer whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Buyer whereDeletedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Buyer whereEmail($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Buyer whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Buyer whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Buyer wherePassword($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Buyer whereRememberToken($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Buyer whereUpdatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Buyer whereVerificationToken($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Buyer whereVerified($value)
 * @mixin \Eloquent
 */
class Buyer extends User
{
    public $transformer=BuyerTransformer::class;
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new buyerScope);
    }

    //One To Many
    public function transactions()
    {
        return $this->hasMany(Transaction::class);
    }
}
