<?php

namespace App;


use App\Scopes\SellerScope;
use App\Transformers\SellerTransformer;

/**
 * App\Seller
 *
 * @property int $id
 * @property string $name
 * @property string $email
 * @property string $password
 * @property string|null $remember_token
 * @property string $verified
 * @property string|null $verification_token
 * @property string $admin
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property \Illuminate\Support\Carbon|null $deleted_at
 * @property-read \Illuminate\Notifications\DatabaseNotificationCollection|\Illuminate\Notifications\DatabaseNotification[] $notifications
 * @property-read int|null $notifications_count
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Product[] $products
 * @property-read int|null $products_count
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Seller newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Seller newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Seller query()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Seller whereAdmin($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Seller whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Seller whereDeletedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Seller whereEmail($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Seller whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Seller whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Seller wherePassword($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Seller whereRememberToken($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Seller whereUpdatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Seller whereVerificationToken($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Seller whereVerified($value)
 * @mixin \Eloquent
 */
class Seller extends User
{
    public $transformer=SellerTransformer::class;
    static protected function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static ::addGlobalScope(new SellerScope);
    }

    //One To Many
    public function products(){
        return $this->hasMany(Product::class);
    }
}
